Add: Server auth private chat demo
indiest/ue4-channeld-demo pull request #8
Opened 2022-07-28 09:48 UTC by Augkit

Add: Server auth private chat demo
Modified: Record of channel connection is exported to blueprint
Fixed: #5 Delete message object when end of incoming dequeue

2022-07-29 02:41 UTC, indiest commented on Plugins/ChanneldUE/Source/ChanneldUE/ChannelDataView.cpp
> +		if (static_cast<channeldpb::ChannelType>(Pair.Value.ChannelType) ==Provider->GetChannelType())
之后我会把IChannelDataProvider.GetChannelType返回类型改成EChanneldChannelType

2022-07-29 03:07 UTC, indiest requested changes
增加了一些修改建议

2022-07-29 03:07 UTC, indiest commented on Plugins/ChanneldUE/Source/ChanneldUE/ChanneldGameInstanceSubsystem.cpp
> +void UChanneldGameInstanceSubsystem::Broadcast(int32 ChId, int32 ClientConnId, UProtoMessageObject* MessageObject,
该方法只能由服务端调用，需要修改名称为ServerBroadcast，并增加检查，防止客户端调用

2022-07-29 03:07 UTC, indiest commented on Source/ChanneldIntegration/ChanneldIntegrationGameModeBase.cpp
> +		int32 ConnId = UKismetStringLibrary::Conv_StringToInt(UGameplayStatics::ParseOption(Options, TEXT("connid")).TrimStartAndEnd());
读取后的ConnId用于何处？如果存在connid，客户端仍然可以连接

2022-07-29 03:07 UTC, indiest commented on Source/ChanneldIntegration/ChanneldIntegrationGameModeBase.cpp
> +	if (GetWorld()->GetNetMode() == NM_DedicatedServer)
此处逻辑总是在服务端执行，不需要增加判断

2022-07-29 03:07 UTC, indiest commented on Source/ChanneldIntegration/ChanneldIntegrationGameModeBase.cpp
> +				ServerAuthPlayerController->ChanneldConnid = ConnId;
ChanneldConnid -> ChanneldConnId

2022-07-29 07:14 UTC, Augkit commented on Source/ChanneldIntegration/ChanneldIntegrationGameModeBase.cpp
> +		int32 ConnId = UKismetStringLibrary::Conv_StringToInt(UGameplayStatics::ParseOption(Options, TEXT("connid")).TrimStartAndEnd());
此处用于校验connid的合法性，如果id不合法则server可以将对应connid从channeld断开连接

2022-07-31 00:14 UTC, indiest requested changes
还剩几处小修改建议

2022-07-31 00:14 UTC, indiest commented on Plugins/ChanneldUE/Source/ChanneldUE/ChanneldConnection.cpp
>  		// All connections without owner sub to the owned channel
Connection没有owner的概念

2022-07-31 00:14 UTC, indiest commented on Plugins/ChanneldUE/Source/ChanneldUE/ChanneldConnection.cpp
> +		if (ensureMsgf(ExistingOwnedChannel != nullptr, TEXT("Dont own the channel: %d, SubscribedToChannelResultMessage will only be sent to channel owners or subscribers"), ChId))
Dont不是被动的意思。这里表述大概是"Received other connnection's SubscribedToChannelResultMessage  while not owning the channel"

2022-07-31 00:14 UTC, indiest commented on Plugins/ChanneldUE/Source/ChanneldUE/ChanneldGameInstanceSubsystem.cpp
> +	if (GetWorld()->GetNetMode() == NM_Client)
此处这样判断和ConnectionInstance->IsClient()会有什么区别？

2022-08-01 02:52 UTC, indiest approved these changes
Finished the first version of the subsystem framework

2022-08-01 02:52 UTC, merged